"use client";
import { useEffect, useMemo, useState } from "react";
type Mover = { symbol: string; name: string; price: string; change: number; volume: string; sector: string };
const movers: Mover[] = [
  { symbol:"NVDA", name:"NVIDIA Corporation", price:"$129.84", change:5.92, volume:"286.4M", sector:"Technology" }, { symbol:"SMCI", name:"Super Micro Computer", price:"$41.92", change:5.21, volume:"52.1M", sector:"Technology" }, { symbol:"PLTR", name:"Palantir Technologies", price:"$24.36", change:4.86, volume:"68.8M", sector:"Technology" }, { symbol:"TSLA", name:"Tesla, Inc.", price:"$248.98", change:4.18, volume:"111.6M", sector:"Consumer" }, { symbol:"COIN", name:"Coinbase Global", price:"$213.09", change:3.75, volume:"14.8M", sector:"Financials" }, { symbol:"AMD", name:"Advanced Micro Devices", price:"$162.31", change:3.51, volume:"62.3M", sector:"Technology" }, { symbol:"RIVN", name:"Rivian Automotive", price:"$14.82", change:3.19, volume:"37.2M", sector:"Consumer" }, { symbol:"SOFI", name:"SoFi Technologies", price:"$8.24", change:2.87, volume:"46.9M", sector:"Financials" }, { symbol:"MARA", name:"Marathon Digital", price:"$19.48", change:2.64, volume:"29.6M", sector:"Financials" }, { symbol:"ARM", name:"Arm Holdings", price:"$118.75", change:2.31, volume:"12.4M", sector:"Technology" },
  { symbol:"BA", name:"Boeing Company", price:"$178.24", change:-2.18, volume:"8.3M", sector:"Industrials" }, { symbol:"DIS", name:"Walt Disney Company", price:"$104.61", change:-2.44, volume:"11.7M", sector:"Communication" }, { symbol:"NKE", name:"NIKE, Inc.", price:"$74.18", change:-2.76, volume:"13.1M", sector:"Consumer" }, { symbol:"PFE", name:"Pfizer Inc.", price:"$27.93", change:-3.08, volume:"34.9M", sector:"Healthcare" }, { symbol:"BABA", name:"Alibaba Group", price:"$78.56", change:-3.42, volume:"20.5M", sector:"Consumer" }, { symbol:"INTC", name:"Intel Corporation", price:"$21.67", change:-3.85, volume:"79.2M", sector:"Technology" }, { symbol:"SNAP", name:"Snap Inc.", price:"$10.71", change:-4.11, volume:"31.8M", sector:"Communication" }, { symbol:"SHOP", name:"Shopify Inc.", price:"$67.89", change:-4.54, volume:"10.9M", sector:"Technology" }, { symbol:"MRNA", name:"Moderna, Inc.", price:"$109.45", change:-5.06, volume:"9.4M", sector:"Healthcare" }, { symbol:"WBD", name:"Warner Bros. Discovery", price:"$8.17", change:-5.83, volume:"25.7M", sector:"Communication" },
];
const initialIndices = [{ name:"S&P 500", symbol:"I:SPX", value:"—", change:"Latest close", positive:true }, { name:"NASDAQ 100", symbol:"I:NDX", value:"—", change:"Latest close", positive:true }, { name:"DOW", symbol:"I:DJI", value:"—", change:"Latest close", positive:true }];
export default function Home() {
 const [query,setQuery]=useState(""); const [filter,setFilter]=useState<"all"|"up"|"down">("all");
 const [indices,setIndices]=useState(initialIndices); const [indexStatus,setIndexStatus]=useState("Refreshing every minute");
 useEffect(()=>{let active=true; const refresh=async()=>{try{const response=await fetch("/api/market-indices"); const payload=await response.json(); if(!response.ok) throw new Error(payload.error); if(!active)return; const bySymbol=new Map<string,{symbol:string;value:number|null;changePercent:number|null}>((payload.quotes??[]).map((quote:{symbol:string;value:number|null;changePercent:number|null})=>[quote.symbol,quote])); setIndices(initialIndices.map(index=>{const quote=bySymbol.get(index.symbol); if(!quote||quote.value===null)return index; return {...index,value:quote.value.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}),change:quote.changePercent===null?"Latest close":`${quote.changePercent>=0?"+":"−"}${Math.abs(quote.changePercent).toFixed(2)}%`,positive:(quote.changePercent??0)>=0};})); setIndexStatus(`Updated ${new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}`);}catch{if(active)setIndexStatus("Latest close unavailable");}}; refresh(); const timer=window.setInterval(refresh,60000); return()=>{active=false;window.clearInterval(timer);};},[]);
 const results=useMemo(()=>movers.filter(m=>`${m.symbol} ${m.name}`.toLowerCase().includes(query.toLowerCase())&&(filter==="all"||(filter==="up"?m.change>0:m.change<0))),[query,filter]);
 return <main><nav className="nav shell"><a className="brand" href="#top"><span className="brand-mark">M</span>Market<span>Pulse</span></a><div className="nav-meta"><span className="signal"><i /> MARKET OPEN</span><span>Friday, Aug 22</span></div></nav>
 <section id="top" className="hero shell"><div><p className="eyebrow">US EQUITIES / LIVE SNAPSHOT</p><h1>Follow the market’s<br/><em>biggest moves.</em></h1><p className="intro">A focused view of today’s most active stocks, updated throughout the trading session.</p></div><div className="market-card"><span className="card-label">MARKET PULSE</span><strong>Balanced risk-on session</strong><p>Technology leads while defensive sectors lag.</p><div className="pulse-bars"><b/><b/><b/><b/><b/><b/><b/><b/></div></div></section>
 <section className="index-strip"><div className="shell index-grid">{indices.map(index=><div className="index" key={index.symbol}><span>{index.name}</span><strong>{index.value}</strong><em className={index.positive?"positive":"negative"}>{index.change}</em></div>)}</div></section>
 <section className="shell board"><div className="board-heading"><div><p className="eyebrow">TODAY’S LEADERBOARD</p><h2>Top 20 movers</h2></div><p className="updated">Last updated <strong>4:00 PM ET</strong></p></div><div className="controls"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ticker or company" aria-label="Search ticker or company"/><kbd>⌘ K</kbd></label><div className="filters" aria-label="Mover filter">{(["all","up","down"] as const).map(option=><button key={option} onClick={()=>setFilter(option)} className={filter===option?"active":""}>{option==="all"?"All movers":option==="up"?"Gainers":"Losers"}</button>)}</div></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Company</th><th>Last price</th><th>Day change</th><th>Volume</th><th>Sector</th></tr></thead><tbody>{results.map(m=><tr key={m.symbol}><td className="rank">{movers.indexOf(m)+1}</td><td><div className="company"><span className="ticker">{m.symbol.slice(0,1)}</span><div><strong>{m.symbol}</strong><small>{m.name}</small></div></div></td><td className="price">{m.price}</td><td><span className={m.change<0?"change down":"change up"}>{m.change>0?"+":""}{m.change.toFixed(2)}%</span></td><td>{m.volume}</td><td><span className="sector">{m.sector}</span></td></tr>)}</tbody></table>{results.length===0&&<div className="empty">No matching ticker found. Try a symbol like NVDA or TSLA.</div>}</div></section><footer className="shell"><span>MARKETPULSE</span><p>Market data is delayed and for informational purposes only. Not investment advice.</p><span>© 2026</span></footer></main>;
}
