"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

type Research = { symbol: string; detail: { name?: string; description?: string; market_cap?: number; primary_exchange?: string; type?: string; homepage_url?: string } | null; previousClose: { c?: number; o?: number; h?: number; l?: number; v?: number; t?: number } | null; news: Array<{ title: string; url: string; source: string; publishedAt: string }> };
export default function ResearchPage({ params }: { params: { symbol: string } }) {
  const symbol = decodeURIComponent(params.symbol).toUpperCase(); const [data, setData] = useState<Research | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/ticker/${encodeURIComponent(symbol)}`).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData(payload); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Could not load ticker research.")); }, [symbol]);
  const detail = data?.detail; const bar = data?.previousClose; const change = bar?.o && bar.c ? ((bar.c - bar.o) / bar.o) * 100 : null;
  return <main><nav className="nav shell"><Link className="brand" href="/"><span className="brand-mark">M</span>Market<span>Pulse</span></Link><div className="nav-meta"><Link className="back-link" href="/">← Dashboard</Link></div></nav><section className="shell research-hero"><Link className="eyebrow back-link" href="/">← Back to dashboard</Link><p className="eyebrow">TICKER RESEARCH / MASSIVE FREE TIER</p><h1>{symbol}<em>{detail?.name ? ` · ${detail.name}` : ""}</em></h1><p className="research-note">A compact research view built from reference data, the latest available completed session, and recent headlines.</p></section>{error ? <div className="shell empty-copy">{error}</div> : <section className="shell research-grid"><div className="research-main"><div className="metric-grid"><div><span>Latest close</span><strong>{bar?.c != null ? `$${bar.c.toFixed(2)}` : "—"}</strong></div><div><span>Session change</span><strong className={change != null && change < 0 ? "negative" : "positive"}>{change != null ? `${change >= 0 ? "+" : ""}${change.toFixed(2)}%` : "—"}</strong></div><div><span>Volume</span><strong>{bar?.v != null ? bar.v.toLocaleString() : "—"}</strong></div></div><article className="research-card"><p className="eyebrow">ABOUT THE COMPANY</p><h2>{detail?.name ?? symbol}</h2><p>{detail?.description ?? "Company description is not available for this ticker on the current data plan."}</p>{detail?.homepage_url && <a href={detail.homepage_url} target="_blank" rel="noreferrer">Company website ↗</a>}</article></div><aside className="research-card"><p className="eyebrow">PROFILE</p><dl><dt>Exchange</dt><dd>{detail?.primary_exchange ?? "—"}</dd><dt>Security type</dt><dd>{detail?.type ?? "—"}</dd><dt>Market cap</dt><dd>{detail?.market_cap ? `$${(detail.market_cap / 1e9).toFixed(1)}B` : "—"}</dd></dl></aside></section>}<section className="shell research-news"><p className="eyebrow">RECENT NEWS</p><h2>What’s being reported</h2>{data?.news.length ? data.news.map((item,i)=><a className="news-item" href={item.url} target="_blank" rel="noreferrer" key={`${item.url}-${i}`}><span>{item.source}</span><strong>{item.title}</strong></a>) : <p className="empty-copy">Recent ticker-specific headlines will appear here.</p>}</section><footer className="shell"><span>MARKETPULSE</span><p>Market data is delayed and for informational purposes only. Not investment advice.</p><span>© 2026</span></footer></main>;
}
